### ISSUE TITLE
Diona don't regen.

### ISSUE THREAD

**Issue by KhalidGrey** [jamiedigweed/NSS-Phoenix#231]
What happened: Several times now, dioneae remain unaffected by radiation and are only fed by light. Nothing heals via exposure.

What did you expect to happen: Heal/regenerate from light exposure or radiation exposure. Specifically brute and toxin damage.

Steps to Reproduce: Get poisoned, get beat half to death, then stand in a radiation storm. Repeat process for light sources.

**Comment by Ishap** [comment]
Assuming non-issue due to being unable to reproduce.
