### ISSUE TITLE
LOOC Colors

### ISSUE THREAD

**Issue by Lorwp** [jamiedigweed/NSS-Phoenix#283]
Recently there was some quick discussion in OOC about possibly changing the color of LOOC in game for a couple of reasons, including how hard it can be to see on some monitors. I've had a look at solving this issue in 24422a138ff9c5405c193c9b4e65f19f352b91cf that i ended up getting a decently nice color in (That is shown below). But i'll leave it up for discussion here.
![ei7p4nv](https://cloud.githubusercontent.com/assets/8052896/6425172/2dc6ddbc-bf71-11e4-9dd9-13c5b8a71b0e.png)

**Comment by W3bster** [comment]
Going to review later in the morning and verify with staff.

**Comment by Codingale** [comment]
They asked for comments, however I have none, and haven't heard complaints for LOOC being changed in a while.

**Comment by Lorwp** [comment]
Indeed, though i personally think maybe the color is slightly too faint, it's not anything that *needs* to be changed
