### ISSUE TITLE
Supermatter monitor doesn't stop on core ejection.

### ISSUE THREAD

**Issue by bloxgate** [jamiedigweed/NSS-Phoenix#326]
After ejecting the supermatter the monitor continued to alert us to its instability for several minutes, until it reached 11% at which point it stopped.

**Comment by Codingale** [comment]
That is actually intended I think... we had the suppermatter eject once and hit the R&D level... though it's easily fixed.

**Comment by Codingale** [comment]
When it's merged it'll close it for you @bloxgate
